services:
  postgres:
    image: postgres:17
    container_name: focusflow-postgres
    environment:
      POSTGRES_DB: focusflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - focusflow_postgres_data:/var/lib/postgresql/data

volumes:
  focusflow_postgres_data: